/*!
 * SAP UI development toolkit for HTML5 (SAPUI5)
 * 
 * (c) Copyright 2009-2014 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.viz.ui5.controls.VizFrame");jQuery.sap.require("sap.viz.library");jQuery.sap.require("sap.viz.ui5.controls.common.BaseControl");sap.viz.ui5.controls.common.BaseControl.extend("sap.viz.ui5.controls.VizFrame",{metadata:{publicMethods:["getVizUid","vizUpdate","vizSelection"],library:"sap.viz",properties:{"vizType":{type:"string",group:"Misc",defaultValue:null},"vizProperties":{type:"string",group:"Misc",defaultValue:null}},aggregations:{"dataset":{type:"sap.viz.ui5.data.Dataset",multiple:false},"feeds":{type:"sap.viz.ui5.controls.common.feeds.FeedItem",multiple:true,singularName:"feed"}},events:{"renderComplete":{},"selectData":{},"deselectData":{}}}});sap.viz.ui5.controls.VizFrame.M_EVENTS={'renderComplete':'renderComplete','selectData':'selectData','deselectData':'deselectData'};jQuery.sap.require("sap.viz.ui5.controls.common.feeds.AnalysisObject");jQuery.sap.require("sap.viz.ui5.controls.common.feeds.FeedItem");jQuery.sap.require("sap.viz.ui5.controls.common.helpers.VizControlsHelper");
sap.viz.ui5.controls.VizFrame.prototype.init=function(){sap.viz.ui5.controls.common.BaseControl.prototype.init.apply(this,arguments);this._vizFrame=null;this._onThemeChanged=jQuery.proxy(this._applyTheme,this);sap.ui.getCore().attachThemeChanged(this._onThemeChanged);this._clearVariables()};
sap.viz.ui5.controls.VizFrame.prototype.applySettings=function(){sap.ui.core.Control.prototype.applySettings.apply(this,arguments);if(!this._vizFrame){this._createVizFrame()}};
sap.viz.ui5.controls.VizFrame.prototype.exit=function(){sap.viz.ui5.controls.common.BaseControl.prototype.exit.apply(this,arguments);sap.ui.getCore().detachThemeChanged(this._onThemeChanged);this._clearVariables()};
sap.viz.ui5.controls.VizFrame.prototype._clearVariables=function(){this._vizFrame$=null;this._vizCreated=false;this._clearRequestedProperties();this._cachedDataset=null};
sap.viz.ui5.controls.VizFrame.prototype._clearRequestedProperties=function(){this._requestedVizType='info/column';this._requestedVizProperties=null};
sap.viz.ui5.controls.VizFrame.prototype.getVizUid=function(){if(this._vizFrame){return this._vizFrame.vizUid()}else{return null}};
sap.viz.ui5.controls.VizFrame.prototype.setUiConfig=function(u){sap.viz.ui5.controls.common.BaseControl.prototype.setUiConfig.apply(this,arguments)};
sap.viz.ui5.controls.VizFrame.prototype.getVizType=function(){var v=this._getVizType();if(v.indexOf('info/')===0){v=v.substr('info/'.length)}return v};
sap.viz.ui5.controls.VizFrame.prototype._getVizType=function(){var v;if(this._vizFrame&&this._vizFrame.vizType()){v=this._vizFrame.vizType()}else{v=this._requestedVizType}return v};
sap.viz.ui5.controls.VizFrame.prototype.setVizType=function(v){if(v&&v.indexOf('info/')===-1){v='info/'+v}if(this._vizFrame&&this._vizCreated){try{this._vizFrame.vizType(v)}catch(e){this._requestedVizType=v}}else{this._requestedVizType=v}return this};
sap.viz.ui5.controls.VizFrame.prototype.getVizProperties=function(){if(this._vizFrame){return jQuery.extend(true,{},this._vizFrame.vizProperties()||{},this._requestedVizProperties||{})}else{return this._requestedVizProperties}};
sap.viz.ui5.controls.VizFrame.prototype.setVizProperties=function(v){if(this._vizFrame&&this._vizCreated){try{this._vizFrame.vizProperties(v)}catch(e){this._requestedVizProperties=v}}else{this._requestedVizProperties=jQuery.extend(true,this._requestedVizProperties||{},v||{})}return this};
sap.viz.ui5.controls.VizFrame.prototype.getFeeds=function(){var f=this.getAggregation('feeds');if(f&&this._vizFrame&&this._vizCreated){f=sap.viz.ui5.controls.common.feeds.FeedItem.toFeeds(this._vizFrame.feeds())}sap.viz.ui5.controls.common.helpers.VizControlsHelper.updateFeedsByAAIndex(this._getVizType(),f);return f};
sap.viz.ui5.controls.VizFrame.prototype.vizSelection=function(p,a){if(this._vizFrame&&this._vizCreated){try{var r=this._vizFrame.vizSelection.apply(this._vizFrame,arguments);if(r===this._vizFrame){r=this}}catch(e){return null}return r}else{return null}};
sap.viz.ui5.controls.VizFrame.prototype.vizUpdate=function(o){if(this._vizFrame){if(o.data||o.feeds){if(o.properties){this._requestedVizProperties=jQuery.extend(true,this._requestedVizProperties||{},o.properties||{})}if(o.data){this.setDataset(o.data)}if(o.feeds){this._setFeeds(o.feeds)}}else{this._vizFrame.vizUpdate(o)}}};
sap.viz.ui5.controls.VizFrame.prototype._createVizFrame=function(o){this._applyTheme();var V=sap.viz.controls.frame.VizFrame;var G=sap.viz.controls.common.config.GlobalConfig;var c='ui5-viz-controls';this._vizFrame$=jQuery(document.createElement('div'));this._vizFrame$.addClass(c+'-viz-frame');var v=G.defaultUIConfig(G.DEFAULT_UICONFIG_TYPE_FRAME);v.enableFilterMenu=false;v.enableFilterBar=false;v.enableSettingButton=false;v.enableFullScreenButton=false;v.enablePlayControl=false;v.controls.chart.enableMorphing=false;v.controls.chart.enableTrellis=false;v.controls.contextMenu.menu=[["direction","stacking"],["legend","datalabels"]];var u=this.getUiConfig();if(u){var d=v.controls.chart.defaultProperties;if(u.applicationSet==='fiori'){v.enableContextMenu=false;d.tooltip.visible=false;d.plotArea.colorPalette=['#5cbae6','#b6d957','#fac364','#8cd3ff','#d998cb','#fade64','#93b9c6','#d9d6c7','#52bacc','#dce65c','#98aafb'];d.plotArea.isFixedDataPointSize=true;d.interaction={'behaviorType':'sFinBehavior','selectability':{'mode':'multiple'}}}}jQuery(this._app$).attr("data-sap-ui-preserve",true);var a=this._vizFrame=new V(this._vizFrame$.get(0),v);this._registerControl('sap.viz.controls.frame.VizFrame',this._vizFrame);a.vizOn('selectData',jQuery.proxy(function(e){this.fireEvent("selectData",e)},this));a.vizOn('deselectData',jQuery.proxy(function(e){this.fireEvent("deselectData",e)},this));a.vizOn('initialized',jQuery.proxy(function(e){this.fireEvent("renderComplete",e)},this));return a};
sap.viz.ui5.controls.VizFrame.prototype._updateVizFrame=function(){var o={'type':this._getVizType()};var d=this._getFlatDataSet();var f=this.getAggregation('feeds');if(d&&f){o.data=d;o.feeds=sap.viz.ui5.controls.common.helpers.VizControlsHelper.getFeedInstances(f)}if(this._requestedVizProperties){o.properties=this._requestedVizProperties}if(!this._vizCreated){if(o.data&&o.feeds){this._vizCreated=true;this._vizFrame.createViz(o);this._clearRequestedProperties()}}else{this._vizFrame.vizUpdate(o);this._clearRequestedProperties()}};
sap.viz.ui5.controls.VizFrame.prototype._getFlatDataSet=function(){var d=this.getDataset();if(d){return d.getVIZFlatDataset()}else{return null}};
sap.viz.ui5.controls.VizFrame.prototype._createChildren=function(){this._vizFrame$.appendTo(this._app$);this._updateVizFrame()};
sap.viz.ui5.controls.VizFrame.prototype._updateChildren=function(){this._updateVizFrame()};
sap.viz.ui5.controls.VizFrame.prototype._setFeeds=function(f){this.destroyFeeds();if(f&&f.length){for(var i=0;i<f.length;i++){this.addFeed(f[i])}}return this};
sap.viz.ui5.controls.VizFrame.prototype._applyTheme=function(){var t=sap.ui.getCore().getConfiguration().getTheme();if(t==='sap_hcb'){var p=this.getVizProperties()||{};p.general=p.general||{};p.general.background=p.general.background||{};p.general.background.color='#000000';this.setVizProperties(p)}};
sap.viz.ui5.controls.VizFrame.prototype._validateSize=function(){if(!this._app$){return}var s={'width':this.$().width(),'height':this.$().height()};var a={'width':this._app$.width(),'height':this._app$.height()};if(this._vizFrame){this._vizFrame.size({'width':a.width,'height':a.height})}else{this._vizFrame$.css({'width':a.width+'px','height':a.height+'px'})}};
