//
//  ACError.h
//  Error codes used by AppConnect
//
//  Copyright (c) 2013 MobileIron. All rights reserved.
//
//  YOUR USE AND DISTRIBUTION OF THIS SOFTWARE IS SUBJECT TO THE SOFTWARE DEVELOPMENT KIT (SDK) AGREEMENT BETWEEN
//  YOU AND MOBILE IRON, INC. (“MI”).  USE OR DISTRIBUTION NOT IN STRICT ACCORDANCE WITH THE AGREEMENT IS PROHIBITED.
//

#import <Foundation/Foundation.h>

extern NSString * const ACErrorDomain;

enum {
    ACE_NO_ERROR = 0,
    ACE_NO_KEYS_ERROR,
    ACE_FILE_TOO_BIG_ERROR,
    ACE_NEGATIVE_FILE_LEN_ERROR,
    ACE_LOW_MEMORY_ERROR,
    ACE_BAD_KEY_OR_CORRUPT_DATA_ERROR,
    ACE_INVALID_ARG,
    ACE_REGULAR_FILE_ONLY_ERROR,
    ACE_INTERNAL_ERROR = 444,
};
